### ISSUE TITLE
Godot 4 is SO BUGGY !!

### ISSUE THREAD

**Issue by mahdisml** [mahdisml/DartGodot#2]
I can't develop DartGodot with broken version of godot.
we must wait for beta release , Godot 4 (vulkan version) is unusable for now and so buggy !

**Comment by gerardwebb** [comment]
Just saw this https://godotengine.org/article/editor-improvements-godot-40.

Is the engine public and stable ?

**Comment by mahdisml** [comment]
there is not beta version yet but source of engine is public , you can build it manually , it has a lot of bug , I think we will all grow old by the time version 4 arrives :((

**Comment by mahdisml** [comment]
> 
> 
> Just saw this https://godotengine.org/article/editor-improvements-godot-40.
> 
> Is the engine public and stable ?

there is no beta version yet but source of engine is public , you can build it manually , it has a lot of bug , I think we will all grow old by the time version 4 arrives :((

**Comment by mjablecnik** [comment]
@mahdisml Hello, in latest Godot blog article I see that first beta release will be released early (in september). 
So do you will continue in next development of DartGodot? :)

**Comment by mahdisml** [comment]
> @mahdisml Hello, in latest Godot blog article I see that first beta release will be released early (in september). So do you will continue in next development of DartGodot? :)

hmm Yes, when the beta version is released, I will start my work, but I am a little disappointed because of dart performance.
its very slow (80~90% javascript performance).

**Comment by mjablecnik** [comment]
@mahdisml Really? And what benchmark did you try? I think that Dart performance is not so bad compared to other languages..:
https://programming-language-benchmarks.vercel.app/dart-vs-csharp
https://programming-language-benchmarks.vercel.app/dart-vs-java
https://programming-language-benchmarks.vercel.app/dart-vs-python
https://programming-language-benchmarks.vercel.app/dart-vs-ruby
https://programming-language-benchmarks.vercel.app/dart-vs-typescript

**Comment by mahdisml** [comment]
> @mahdisml Really? And what benchmark did you try? I think that Dart performance is not so bad compared to other languages..: https://programming-language-benchmarks.vercel.app/dart-vs-csharp https://programming-language-benchmarks.vercel.app/dart-vs-java https://programming-language-benchmarks.vercel.app/dart-vs-python https://programming-language-benchmarks.vercel.app/dart-vs-ruby https://programming-language-benchmarks.vercel.app/dart-vs-typescript

haha ! dart cant compete with C# and Java (dart is javascript competitor) , its slow : 
https://www.reddit.com/r/dartlang/comments/jjlsvy/dart_language_speed_vs_other_languages/
https://github.com/drujensen/fib

but it's usable for 2D game (same as javascript).
My problem is Dart AOT have Serious limitations and i cant use it in DartGodot (i used DartJS which makes it slower than JavaScript).

**Comment by mjablecnik** [comment]
@mahdisml Oh! So you mean DartJS and not Dart AOT!. Ok, DartJS can be maybe slower (I didn't try it).
And can you please describe me what limitation have Dart AOT? :)
Thanks

**Comment by mahdisml** [comment]
> @mahdisml Oh! So you mean DartJS and not Dart AOT!. Ok, DartJS can be maybe slower (I didn't try it). And can you please describe me what limitation have Dart AOT? :) Thanks

When I was working on DartGodot, Dart could not create native dynamic libraries.

**Comment by nxuv** [comment]
Well, it's already been a bit since godot 4 beta came out and with c#
Seems pretty stable to start porting

**Comment by mahdisml** [comment]
> Well, it's already been a bit since godot 4 beta came out and with c# Seems pretty stable to start porting

i have problem with godot 4 :((((
https://github.com/godotengine/godot/issues/66685

**Comment by nxuv** [comment]
Wow, that's rough. My instance of godot 4 works almost fine, except fact it duplicates c# scripts references

**Comment by nxuv** [comment]
Will dart:ffi lib be used in gd4 bindings?
Like, logically it's much easier to do it that way and just typedef it all to usual names

**Comment by mahdisml** [comment]
> dart:ffi

Dart has changed a lot, and hopefully dart:ffi has gotten better.
I hope it can be worked with

**Comment by nxuv** [comment]
Dart is a nice language but i really don't understand why do such limited amount of types
Like, why if you do something like that u need to go full on it, like typescript
Or just keep it as all big boy langs and do full types (also no char is sad a bit)

**Comment by damywise** [comment]
We do have [Char](https://api.dart.dev/stable/2.18.2/dart-ffi/Char-class.html)  and [many ](https://api.dart.dev/stable/2.18.2/dart-ffi/dart-ffi-library.html), [other](https://api.dart.dev/stable/2.18.2/dart-typed_data/dart-typed_data-library.html)

**Comment by nxuv** [comment]
Dartffi is still like a band-aid, I'm talking primitive types that u can have with no external lib or something

**Comment by damywise** [comment]
What problem have you encountered because of that?

**Comment by nxuv** [comment]
Using dart:ffi as normal types can be difficult sometimes.
But overall, I'm just a unhappy gremlin who likes everything being nicely strictly typed

**Comment by gururise** [comment]
Any traction on this issue now that Godot 4 is nearing it's final BETA release and about to go the Release Candidate stage?

**Comment by guyluz11** [comment]
godot 4 is in Release candidate

https://godotengine.org/article/release-candidate-godot-4-0-rc-3/
